[character]
format = '[â–¶](#ff761a) '

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''
ignore_branches = ['master', 'main']

[git_status]
format = '([$all_status$ahead_behind]($style) )'
#conflicted = 'ğŸ³'
ahead = '*'
behind = '*'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = '*'
#staged = '[++\($count\)](green)'
#renamed = 'ğŸ‘…'
#deleted = 'ğŸ—‘'

# [frame]
# format = 'on [$symbol($profile )(\($region\) )]($style)'
# style = 'bold blue'
# symbol = 'ğŸ–½ '
#
# current
